### ISSUE TITLE
Could not load type 'Microsoft.ServiceFabric.Data.Collections.IReliableConcurrentQueue`

### ISSUE THREAD

**Issue by justinpatten** [loekd/ServiceFabric.Mocks#21]
After upgrading the fabric version and this NuGet package, I am getting the following error in VSTS builds:

Could not load type 'Microsoft.ServiceFabric.Data.Collections.IReliableConcurrentQueue`1' from assembly 'Microsoft.ServiceFabric.Data.Interfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Stack Trace:
at ServiceFabric.Mocks.MockReliableStateManager.<>c__DisplayClass25_0`1.<GetOrAddAsync>b__0(Uri collectionName)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at ServiceFabric.Mocks.MockReliableStateManager.GetOrAddAsync[T](ITransaction tx, String name)

It runs fine locally, so I am just looking for any pointers on what could be wrong in the hosted build.

**Comment by loekd** [comment]
I suspect this has something to do with the fact that the hosted vs2017 agents have a beta version of the sf sdk installed.

This creates the other issue as well. I'll see if the beta sdk can be downloaded already.

Which version of SF do you run?

**Comment by justinpatten** [comment]
I rolled back the NuGet package for ServiceFabric.Mocks to 1.6.0 and then it passed on the server. However, that broke the tests running locally. Looks like I need to roll back my local SDK to what is on the build server for now.

Thanks.

**Comment by kotvisbj** [comment]
I have the same problem as Justin.  I did the same thing because I upgraded my stateless APIs to .net core.  So I can't really go back.  It looks like the old build agent wouldn't build the .net core APIs and the new (hosted vs2017) one won't run the tests.  Oh to be on the cutting edge.  I am not in production yet so I am going to try to update the binaries to the latest version otherwise I may try to do a PR if you don't have it figured out already.

**Comment by loekd** [comment]
I've published a preview package that targets the preview SDK and Nuget packages. That runs fine on the VS2017 build agents.
https://www.nuget.org/packages/ServiceFabric.Mocks/2.2.0-preview

**Comment by loekd** [comment]
@kotvisbj please retry your run on hosted VS2017, they've fixed the TypeLoadException issue, so the tests should run fine now.

@justinpatten can you also try building on hosted VS2017?

**Comment by ben-kotvis** [comment]
@loekd Do you have to do something for the build agent to be updated?  I am still getting the error.  To be clear, I haven't updated any packages.  I just re-ran the failing tests in my builds.

**Comment by ben-kotvis** [comment]
Another update on my end.  Updating my packages has fixed my problems in VSTS and dev machine.  I am using 2.2.0-preview.

**Comment by justinpatten** [comment]
We aren't in a position to upgrade to the preview service fabric SDK, which is what the 2.2.0-preview requires. I will live in my current situation until the VSTS agents are updated.

Thanks.
